server:
  type: default
  applicationConnectors:
    - type: http
      port: 0
  adminConnectors:
    - type: http
      port: 0

kafka-producer:
  bootstrapServer: 127.0.0.1:9092
  topic: data-input
  acks: all
  retries: 2147483647 # int max value
  maxInFlightRequestsPerConnection: 1
  maxPollBlockTime: 10s