server:
  type: default
  applicationConnectors:
    - type: http
      port: 1001
  adminConnectors:
    - type: http
      port: 1002

kafka-producer:
  bootstrapServer: 127.0.0.1:9092
  topic: data-input
  acks: all
  retries: 2147483647
  maxInFlightRequestsPerConnection: 1
  maxPollBlockTime: 10s